package com.smyy.sharetour.buyer.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smyy.sharetour.buyer.db.Test;
import com.smyy.sharetour.buyer.db.Test2;

import com.smyy.sharetour.buyer.greendao.TestDao;
import com.smyy.sharetour.buyer.greendao.Test2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig test2DaoConfig;

    private final TestDao testDao;
    private final Test2Dao test2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        test2DaoConfig = daoConfigMap.get(Test2Dao.class).clone();
        test2DaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        test2Dao = new Test2Dao(test2DaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(Test2.class, test2Dao);
    }
    
    public void clear() {
        testDaoConfig.clearIdentityScope();
        test2DaoConfig.clearIdentityScope();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public Test2Dao getTest2Dao() {
        return test2Dao;
    }

}
